# /etc/fail2ban/jail.d/supermercados-go.conf

[supermercados-go-auth]
enabled = true
port = http,https
filter = supermercados-go-auth
logpath = /var/log/supermercados-go.log
maxretry = 5
findtime = 600
bantime = 3600
banaction = ufw

[supermercados-go-api]
enabled = true
port = http,https
filter = supermercados-go-api
logpath = /var/log/supermercados-go.log
maxretry = 30
findtime = 60
bantime = 300
banaction = ufw
